In [28]:
liste=[]
i=2000       
while i <=3200:
       if i % 7 == 0 and i % 5 != 0 :
        liste.append(i)
       i+=1   

print(liste)

[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]


In [6]:
n=int(input("donner un nombre "))
a=1
for i in range (1,n+1) :
  a=i*a
print(a)
    



donner un nombre 5
120


In [16]:
n=int(input("donner un nombre"))
for i in range (1,n+1):
 multiple[i]=i*i
print(multiple)

donner un nombre5
{4: 16, 1: 1, 2: 4, 3: 9, 5: 25}


In [8]:
ch=str(input("donner une chaine de caractère"))
n=int(input("donner un entier"))
if n<=len(ch):
 ch=ch[:n]+ch[n+1:]
print(ch)




donner une chaine de caractèreamal
donner un entier0
mal


In [4]:
import numpy as np
x= np.arange(6).reshape(3, 2)
print("Original array elements:")
print(x)
print("Array to list:")
print(x.tolist()) 

Original array elements:
[[0 1]
 [2 3]
 [4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]


In [2]:
import numpy as np
x = np.array([0, 1, 2])
y = np.array([2, 1, 0])
print("\nOriginal array1:")
print(x)
print("\nOriginal array2:")
print(y)
print("\nCovariance matrix of the said arrays:\n",np.cov(x, y))



Original array1:
[0 1 2]

Original array2:
[2 1 0]

Covariance matrix of the said arrays:
 [[ 1. -1.]
 [-1.  1.]]


In [3]:
import math

C= 50
H = 30
D1 = []
result =[]
D0=input("enter the value of D\n")
D1=D0.split(",")
D1 = [int(i) for i in D1]
i=0
l = len(D1)
while(i<l):
    Q = round(math.sqrt((2*C*D1[i])/H))
    result. append(Q)
    i+=1
print("output=",result)


enter the value of D
15,16,17
output= [7, 7, 8]
